### ISSUE TITLE
Documentatie en plannen in het Engels

### ISSUE THREAD

**Issue by BramLeisink** [BramLeisink/rooster-documentation#1]
Moeten de plannen, issues en de documentatie in het Engels? Het heeft wat voordelen, maar misschien is het voor nu nog niet handig. Engels is universeler natuurlijk, maar uiteindelijk praten we gewoon Nederlands. Laat ff weten wat je vind, dan hebben we dit voor nu duidelijk en kunnen we kijken hoe issues werken.

**Comment by BramLeisink** [comment]
Het is makkelijk mogelijk om de documentatiesite tweetalig te maken, maar dat moet elk document dubbel geschreven/aangepast worden.

**Comment by ClickszNL** [comment]
Ligt er natuurlijk wel een beetje aan wat je bereik gaat worden, namelijk als je het alleen in Nederland wilt aanbieden dan kan je natuurlijk beter Nederlands houden, maar als je blik veel groter is, dus echt internationaal dan kan ik je beter adviseren om het in het Engels te zetten en misschien iets van een extensie/plugin er in te bouwen die de website accuraat vertaald.
