### ISSUE TITLE
Is Open-Source veilig genoeg met cijfers?

### ISSUE THREAD

**Issue by QuintenC08** [BramLeisink/rooster-documentation#4]
Als je het compleet open source wil wat ik kan begrijpen zouden mensen niet een manier kunnen vinden om hun cijfers aan te passen. of weet je al iets om dit tegen te gaan?

**Comment by BramLeisink** [comment]
Je hebt zeker een goed punt. Volledig open source is onveiliger dan gesloten. Het is daarom ook niet de bedoeling om de database open source te maken. Deze hosten we zelf/wordt door de school gehost. Elke gebruiker heeft een bepaalde toegang tot de database, leerlingen hebben minder rechten dan een afdelings coördinator.

Alleen als iemand de gebruikersnaam en wachtwoord van iemand met de juiste rechten weet, kan deze een cijfer aanpassen. Alle code die hier voor zorgt kan open source zijn, zolang maar niet bekend wordt wat de inloggegevens van de gebruiker zijn.

# Frontend en Backend 
Daarnaast is er een belangrijk verschil tussen frontend en backend code:

- **Frontend:** Alle frontend code die wordt gerund kan door de gebruiker gevolgd worden, deze wordt namelijk uitgevoerd op het apparaat dat de website bezoekt. De gebruiker kan met wat technische kennis precies zien welke data er in en uit de website gaat. Dit is niet veilig, een gebruiker kan namelijk zelfs tijdelijk de frontend code aanpassen, om de werking hiervan te veranderen.
- **Backend:** Deze code wordt op een server uitgevoerd. Alleen mensen die directe toegang hebben tot de servers kunnen zien wat er op de servers gebeurt. Backend code wordt dus meestal gebruikt om data uit de database op te vragen, of gevoelige data te verwerken.

## Waarom is dan niet alles backend?
Backend is duurder. Als een gebruiker de website bezoekt, kan er volledig gratis code op hun apparaat uitgevoerd worden. De servers worden minder gebruikt en dat is dan goedkoper.

Frontend code is ook (meestal) sneller. Het kost tijd om alle data elke keer naar een datacenter te sturen, daar te verwerken, en dan weer terug te sturen. Door functies direct op de clientside uit te voeren wordt de hele website sneller. Een uitzondering hierop is het bijvoorbeeld verwerken van video of grote aantallen data. Dit is sneller op een snelle server, dan op een telefoon.

# Privacy in het algemeen
Ja, open source zou minder privacy kunnen betekenen. Tegelijkertijd zou iedereen, als ze een foutje in de code vinden, deze meteen kunnen aanpassen. Perfecte open source code en perfecte closed source code is precies even veilig. Vaak kom je hier zelfs sneller wanneer het project open source is.

Hoe open dit project is, blijft een lastig besluit en ik denk dat het goed is hier ook nog niet meteen ergens voor te kiezen, maar eerst vanuit verschillende kanten te kijken wat het beste is.
